# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fluent_dialogue_dora/v1/barge_in.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'fluent_dialogue_dora/v1/barge_in.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&fluent_dialogue_dora/v1/barge_in.proto\x12\x17\x66luent_dialogue_dora.v1\"\xe0\x01\n\x0c\x42\x61rgeInEvent\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x11\n\tstream_id\x18\x03 \x01(\t\x12\x0b\n\x03seq\x18\x04 \x01(\x04\x12\x1b\n\x13playback_request_id\x18\x05 \x01(\t\x12\x1a\n\x12playback_stream_id\x18\x06 \x01(\t\x12\x15\n\rplayed_frames\x18\x07 \x01(\x04\x12\x1d\n\x15\x64\x65tected_sample_index\x18\x08 \x01(\x04\x12\x1a\n\x12speech_probability\x18\t \x01(\x01\"[\n\x12\x42\x61rgeInStreamFinal\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x11\n\tstream_id\x18\x03 \x01(\t\x12\x0b\n\x03seq\x18\x04 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fluent_dialogue_dora.v1.barge_in_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BARGEINEVENT']._serialized_start=68
  _globals['_BARGEINEVENT']._serialized_end=292
  _globals['_BARGEINSTREAMFINAL']._serialized_start=294
  _globals['_BARGEINSTREAMFINAL']._serialized_end=385
# @@protoc_insertion_point(module_scope)
