# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fluent_dialogue_dora/v1/diagnostics.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'fluent_dialogue_dora/v1/diagnostics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)fluent_dialogue_dora/v1/diagnostics.proto\x12\x17\x66luent_dialogue_dora.v1\"\x99\x01\n\nNodeStatus\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x31\n\x05state\x18\x02 \x01(\x0e\x32\".fluent_dialogue_dora.v1.NodeState\x12\x0b\n\x03seq\x18\x03 \x01(\x04\x12\x18\n\x10observed_time_ns\x18\x04 \x01(\x04\x12\x14\n\x07message\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"\xa7\x01\n\x0f\x44iagnosticEvent\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12=\n\x08severity\x18\x02 \x01(\x0e\x32+.fluent_dialogue_dora.v1.DiagnosticSeverity\x12\x0b\n\x03seq\x18\x03 \x01(\x04\x12\x18\n\x10observed_time_ns\x18\x04 \x01(\x04\x12\x0c\n\x04\x63ode\x18\x05 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t*\xb1\x01\n\x12\x44iagnosticSeverity\x12#\n\x1f\x44IAGNOSTIC_SEVERITY_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x44IAGNOSTIC_SEVERITY_OK\x10\x01\x12\x1c\n\x18\x44IAGNOSTIC_SEVERITY_WARN\x10\x02\x12\x1d\n\x19\x44IAGNOSTIC_SEVERITY_ERROR\x10\x03\x12\x1d\n\x19\x44IAGNOSTIC_SEVERITY_FATAL\x10\x04*\xcf\x01\n\tNodeState\x12\x1a\n\x16NODE_STATE_UNSPECIFIED\x10\x00\x12\x17\n\x13NODE_STATE_STARTING\x10\x01\x12\x14\n\x10NODE_STATE_READY\x10\x02\x12\x16\n\x12NODE_STATE_RUNNING\x10\x03\x12\x17\n\x13NODE_STATE_DEGRADED\x10\x04\x12\x17\n\x13NODE_STATE_STOPPING\x10\x05\x12\x16\n\x12NODE_STATE_STOPPED\x10\x06\x12\x15\n\x11NODE_STATE_FAILED\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fluent_dialogue_dora.v1.diagnostics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIAGNOSTICSEVERITY']._serialized_start=397
  _globals['_DIAGNOSTICSEVERITY']._serialized_end=574
  _globals['_NODESTATE']._serialized_start=577
  _globals['_NODESTATE']._serialized_end=784
  _globals['_NODESTATUS']._serialized_start=71
  _globals['_NODESTATUS']._serialized_end=224
  _globals['_DIAGNOSTICEVENT']._serialized_start=227
  _globals['_DIAGNOSTICEVENT']._serialized_end=394
# @@protoc_insertion_point(module_scope)
