# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fluent_dialogue_dora/v1/tts.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'fluent_dialogue_dora/v1/tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fluent_dialogue_dora_contracts.fluent_dialogue_dora.v1 import audio_pb2 as fluent__dialogue__dora_dot_v1_dot_audio__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!fluent_dialogue_dora/v1/tts.proto\x12\x17\x66luent_dialogue_dora.v1\x1a#fluent_dialogue_dora/v1/audio.proto\"\x94\x01\n\x0cTtsTextChunk\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x14\n\x0cuser_turn_id\x18\x03 \x01(\t\x12\x19\n\x11\x61ssistant_turn_id\x18\x04 \x01(\t\x12\x0b\n\x03seq\x18\x05 \x01(\x04\x12\x0c\n\x04text\x18\x06 \x01(\t\x12\x10\n\x08is_final\x18\x07 \x01(\x08\"f\n\x12TtsTextStreamFinal\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0cuser_turn_id\x18\x02 \x01(\t\x12\x19\n\x11\x61ssistant_turn_id\x18\x03 \x01(\t\x12\x0b\n\x03seq\x18\x04 \x01(\x04\"\xb1\x01\n\x15SynthesizedAudioChunk\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x14\n\x0cuser_turn_id\x18\x03 \x01(\t\x12\x19\n\x11\x61ssistant_turn_id\x18\x04 \x01(\t\x12\x0b\n\x03seq\x18\x05 \x01(\x04\x12\x32\n\x05\x61udio\x18\x06 \x01(\x0b\x32#.fluent_dialogue_dora.v1.AudioFrame\"\xbf\x02\n\x1bSynthesizedAudioStreamFinal\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x14\n\x0cuser_turn_id\x18\x03 \x01(\t\x12\x19\n\x11\x61ssistant_turn_id\x18\x04 \x01(\t\x12\x0b\n\x03seq\x18\x05 \x01(\x04\x12\x17\n\x0f\x61udio_source_id\x18\x06 \x01(\t\x12\x17\n\x0f\x61udio_stream_id\x18\x07 \x01(\t\x12\x11\n\taudio_seq\x18\x08 \x01(\x04\x12\x1a\n\x12\x61udio_sample_index\x18\t \x01(\x04\x12\x1d\n\x15\x61udio_capture_time_ns\x18\n \x01(\x04\x12:\n\x0c\x61udio_format\x18\x0b \x01(\x0b\x32$.fluent_dialogue_dora.v1.AudioFormatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fluent_dialogue_dora.v1.tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TTSTEXTCHUNK']._serialized_start=100
  _globals['_TTSTEXTCHUNK']._serialized_end=248
  _globals['_TTSTEXTSTREAMFINAL']._serialized_start=250
  _globals['_TTSTEXTSTREAMFINAL']._serialized_end=352
  _globals['_SYNTHESIZEDAUDIOCHUNK']._serialized_start=355
  _globals['_SYNTHESIZEDAUDIOCHUNK']._serialized_end=532
  _globals['_SYNTHESIZEDAUDIOSTREAMFINAL']._serialized_start=535
  _globals['_SYNTHESIZEDAUDIOSTREAMFINAL']._serialized_end=854
# @@protoc_insertion_point(module_scope)
