# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fluent_audio/v1/session.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'fluent_audio/v1/session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66luent_audio/v1/session.proto\x12\x0f\x66luent_audio.v1\"i\n\x07TurnIds\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0cuser_turn_id\x18\x02 \x01(\t\x12\x1e\n\x11\x61ssistant_turn_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x14\n\x12_assistant_turn_id\"\xd8\x01\n\x11VoiceSessionEvent\x12\x35\n\x05\x65vent\x18\x01 \x01(\x0e\x32&.fluent_audio.v1.VoiceSessionEventKind\x12\x31\n\x05state\x18\x02 \x01(\x0e\x32\".fluent_audio.v1.VoiceSessionState\x12\x0b\n\x03seq\x18\x03 \x01(\x04\x12*\n\x08turn_ids\x18\x04 \x01(\x0b\x32\x18.fluent_audio.v1.TurnIds\x12\x14\n\x07message\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message*\xee\x02\n\x11VoiceSessionState\x12#\n\x1fVOICE_SESSION_STATE_UNSPECIFIED\x10\x00\x12\x1c\n\x18VOICE_SESSION_STATE_IDLE\x10\x01\x12!\n\x1dVOICE_SESSION_STATE_LISTENING\x10\x02\x12%\n!VOICE_SESSION_STATE_USER_SPEAKING\x10\x03\x12$\n VOICE_SESSION_STATE_TRANSCRIBING\x10\x04\x12 \n\x1cVOICE_SESSION_STATE_THINKING\x10\x05\x12 \n\x1cVOICE_SESSION_STATE_SPEAKING\x10\x06\x12#\n\x1fVOICE_SESSION_STATE_INTERRUPTED\x10\x07\x12\x1e\n\x1aVOICE_SESSION_STATE_CLOSED\x10\x08\x12\x1d\n\x19VOICE_SESSION_STATE_ERROR\x10\t*\xba\x03\n\x15VoiceSessionEventKind\x12(\n$VOICE_SESSION_EVENT_KIND_UNSPECIFIED\x10\x00\x12,\n(VOICE_SESSION_EVENT_KIND_SESSION_STARTED\x10\x01\x12*\n&VOICE_SESSION_EVENT_KIND_STATE_CHANGED\x10\x02\x12.\n*VOICE_SESSION_EVENT_KIND_USER_TURN_STARTED\x10\x03\x12\x30\n,VOICE_SESSION_EVENT_KIND_USER_TURN_FINALIZED\x10\x04\x12\x33\n/VOICE_SESSION_EVENT_KIND_ASSISTANT_TURN_STARTED\x10\x05\x12\x35\n1VOICE_SESSION_EVENT_KIND_ASSISTANT_TURN_COMPLETED\x10\x06\x12+\n\'VOICE_SESSION_EVENT_KIND_SESSION_CLOSED\x10\x07\x12\"\n\x1eVOICE_SESSION_EVENT_KIND_ERROR\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fluent_audio.v1.session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOICESESSIONSTATE']._serialized_start=377
  _globals['_VOICESESSIONSTATE']._serialized_end=743
  _globals['_VOICESESSIONEVENTKIND']._serialized_start=746
  _globals['_VOICESESSIONEVENTKIND']._serialized_end=1188
  _globals['_TURNIDS']._serialized_start=50
  _globals['_TURNIDS']._serialized_end=155
  _globals['_VOICESESSIONEVENT']._serialized_start=158
  _globals['_VOICESESSIONEVENT']._serialized_end=374
# @@protoc_insertion_point(module_scope)
